version: "{build}-{branch}"

environment:
  global:
    COMPILE: compile
  matrix:
    - SCALA_VERSION: 2.12.6

init:
  - git config --global core.autocrlf true

build_script:
  - mvn clean package --batch-mode

#test_script:
#  - mvn clean verify --batch-mode

cache:
  - C:\Users\appveyor\.m2

notifications:
  - provider: Email
    to:
      - chenfh5@qq.com
    on_build_success: true
    on_build_failure: true
    on_build_status_changed: true